FROM public.ecr.aws/docker/library/python:3.11

WORKDIR /app

COPY . .

RUN pip install --upgrade pip
RUN pip install poetry
RUN poetry install

EXPOSE 8000

ENTRYPOINT ["/bin/bash", "docker-entrypoint.sh"]
