apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: sample-django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: registry.digitalocean.com/touchoftech/django@sha256:f00fcb430316adeb993a50e84060d3c410346d4a68c9c810128fe5613b182cf3
          ports:
            - containerPort: 8000
